### ISSUE TITLE
.mechanic file doesn't work with Github's personal tokens

### ISSUE THREAD

**Issue by RafalBuchner** [roboDocs/rf-extension-boilerplate#1]
I'm trying to create a `.mechanic` file for my extension that is stored on the private GitHub repo.
I'm trying to do everything as was described in the [extension item documentation](https://robofont.com/documentation/extensions/extension-item-format/).

my infoPath, zipPath and icon entries look like this:
```
infoPath: https://github.com/<user name>/<repo name>/blob/master/<extension-name>.roboFontExt/info.plist?private_token=< token numbers/letters >
zipPath: https://github.com/<user name>/<repo name>/archive/master.zip?private_token=< token numbers/letters >
icon: https://github.com/<user name>/<repo name>/blob/master/icon.png?private_token=< token numbers/letters >
```

After installing the `.mechanic` file, I can see the name of the extension in the Mechanic2 window, but I cannot update my extension. 
I think that the format of those links is not correct, but I cannot find the solution.

**Comment by typemytype** [comment]
the links to the info, zip and icon must work when you are not logged in...

its been a while since Ive used this with GitHub...

**Comment by gferreira** [comment]
the GitHub API is indeed not working anymore… I haven’t figured out the correct syntax yet.

we’ve been using [GitLab](http://gitlab.com/) to serve private extensions, it works fine. please try this:

```yaml
infoPath: https://gitlab.com/api/v4/projects/projectID/repository/files/build/myExtension.roboFontExt%2Finfo.plist/raw?ref=master&private_token=ABCD0123456789XYZ
zipPath: https://gitlab.com/api/v4/projects/projectID/repository/archive.zip?sha=master&private_token=ABCD0123456789XYZ
icon: https://gitlab.com/api/v4/projects/projectID/repository/files/myExtensionMechanicIcon.png/raw?ref=master&private_token=ABCD0123456789XYZ
```

`projectID` is a number which appears in your project’s index page, under the project name.
